In [1]:
import numpy as np
matrix_a = np.array([
    [1, 0, 1],
    [2, 0, 1]
])
#2 by 3
matrix_b = np.array([
    [1, 2],
    [1, 4],
    [1, 2]
])
#3 by 2

In [2]:
matrix_c = np.array([
    [1, 0, 1, 9, 8],
    [2, 0, 1, 0, 21],
    [4, 9, 7, 0, 1],
    [3, 7, 2, 8, 5]
])
#4 by 5
matrix_d = np.array([
    [1, 2, 2],
    [5, 4, 9],
    [2, 2, 0],
    [3, 2, 1],
    [9, 2, 1]
])
#5 by 3

In [3]:
matrix_e = np.array([
    [1, 17, 11],
    [2, 8, 12]
])
#2 by 3
matrix_f = np.array([
    [1, 2],
    [1, 4]
])
#2 by 2

In [4]:
def matrix_multiplication(matrix_a,matrix_b):
    rows_a, cols_a = matrix_a.shape
    rows_b, cols_b = matrix_b.shape
    product_matrix = np.zeros((rows_a, cols_b))
    rows_p, cols_p = product_matrix.shape
    if cols_a != rows_b:
            print('STOP!!!!!!!!!!!!!!!!')
    else:
            for i in range(rows_p):
                for j in range(cols_p):
                    for k in range(cols_a):
                        product_matrix[i][j] = product_matrix[i][j] + matrix_a[i][k]*matrix_b[k][j]
    return(product_matrix)

In [5]:
matrix_multiplication(matrix_a,matrix_b)

array([[2., 4.],
       [3., 6.]])

In [6]:
matrix_multiplication(matrix_c,matrix_d)

array([[102.,  38.,  19.],
       [193.,  48.,  25.],
       [ 72.,  60.,  90.],
       [111.,  64.,  82.]])

In [7]:
matrix_multiplication(matrix_e,matrix_f)

STOP!!!!!!!!!!!!!!!!


array([[0., 0.],
       [0., 0.]])

In [ ]:
rows_timing = 100
cols_timing = 100
random_matrix_100a = np.random.rand(rows_timing, cols_timing)
rows_timingb = 100
cols_timingb = 100
random_matrix_100b = np.random.rand(rows_timing, cols_timing)

In [19]:
import time
start_time = time.time()

matrix_multiplication(random_matrix_100a,random_matrix_100b)

end_time = time.time()
elapsed_time = end_time - start_time

print("Elapsed time: {:.6f} seconds".format(elapsed_time))

Elapsed time: 0.804653 seconds
